INSERT into List (category, title) values (1, "Matt Lee");
INSERT into List (category, title) values (1, "a police officer");
INSERT into List (category, title) values (1, "a cyclist");
INSERT into List (category, title) values (1, "a business person");
INSERT into List (category, title) values (1, "a crowd");
INSERT into List (category, title) values (1, "commuters");

INSERT into List (category, title) values (2, "a park");
INSERT into List (category, title) values (2, "a playground");
INSERT into List (category, title) values (2, "an office building");
INSERT into List (category, title) values (2, "a food truck");
INSERT into List (category, title) values (2, "a bus stop");
INSERT into List (category, title) values (2, "a streetcar");
INSERT into List (category, title) values (2, "a car");
INSERT into List (category, title) values (2, "a truck");
INSERT into List (category, title) values (2, "graffiti");
INSERT into List (category, title) values (2, "a motorcycle");
INSERT into List (category, title) values (2, "a convertible");
INSERT into List (category, title) values (2, "a scooter");
INSERT into List (category, title) values (2, "a condo tower");
INSERT into List (category, title) values (2, "an old house");
INSERT into List (category, title) values (2, "a patio");
INSERT into List (category, title) values (2, "a hot dog cart");
INSERT into List (category, title) values (2, "a street sign");

INSERT into List (category, title) values (3, "a pair of shorts");
INSERT into List (category, title) values (3, "a funny t-shirt");
INSERT into List (category, title) values (3, "a hat");
INSERT into List (category, title) values (3, "a winter coat");
INSERT into List (category, title) values (3, "an umbrella");
INSERT into List (category, title) values (3, "a pair of fancy shoes");
INSERT into List (category, title) values (3, "a cool pair of shoes");
INSERT into List (category, title) values (3, "socks");
INSERT into List (category, title) values (3, "a helmet");
INSERT into List (category, title) values (3, "sandals");
INSERT into List (category, title) values (3, "a sports jacket");
INSERT into List (category, title) values (3, "jewelry");
INSERT into List (category, title) values (3, "a nice tie");

INSERT into List (category, title) values (4, "a tree");
INSERT into List (category, title) values (4, "a dog");
INSERT into List (category, title) values (4, "a cat");
INSERT into List (category, title) values (4, "wildflowers");
INSERT into List (category, title) values (4, "a potted plant");
INSERT into List (category, title) values (4, "a garden");
INSERT into List (category, title) values (4, "a squirrel");
INSERT into List (category, title) values (4, "a bird");
INSERT into List (category, title) values (4, "a body of water");
INSERT into List (category, title) values (4, "a shrub");

INSERT into List (category, title) values (5, "coffee");
INSERT into List (category, title) values (5, "tea");
INSERT into List (category, title) values (5, "pizza");
INSERT into List (category, title) values (5, "beer");
INSERT into List (category, title) values (5, "wine");
INSERT into List (category, title) values (5, "a sandwich");
INSERT into List (category, title) values (5, "a salad");
INSERT into List (category, title) values (5, "cookies");
INSERT into List (category, title) values (5, "a muffin");
INSERT into List (category, title) values (5, "a bagel");
INSERT into List (category, title) values (5, "cake");
INSERT into List (category, title) values (5, "pasta");
INSERT into List (category, title) values (5, "sushi");
INSERT into List (category, title) values (5, "fries");
INSERT into List (category, title) values (5, "ice cream");
INSERT into List (category, title) values (5, "popsicle");
INSERT into List (category, title) values (5, "snacks");
INSERT into List (category, title) values (5, "fruit");
INSERT into List (category, title) values (5, "dinner");
INSERT into List (category, title) values (5, "lunch");
INSERT into List (category, title) values (5, "breakfast");

INSERT into List (category, title) values (6, "a bicycle");
INSERT into List (category, title) values (6, "a musical instrument");
INSERT into List (category, title) values (6, "a fancy rug");
INSERT into List (category, title) values (6, "an office space");
INSERT into List (category, title) values (6, "a lamp");
INSERT into List (category, title) values (6, "a couch");
INSERT into List (category, title) values (6, "a game controller");
INSERT into List (category, title) values (6, "a book shelf");
INSERT into List (category, title) values (6, "a staircase");
INSERT into List (category, title) values (6, "a clock");
INSERT into List (category, title) values (6, "a trinket");
INSERT into List (category, title) values (6, "science equipment");
INSERT into List (category, title) values (6, "tools");
INSERT into List (category, title) values (6, "pots and pans");
INSERT into List (category, title) values (6, "a fridge");
INSERT into List (category, title) values (6, "kitchen utensils");

UPDATE List SET makerid = 1;

UPDATE List SET approved = 1;
